version: '3.8'

services:
  web:
    build: .
    depends_on:
      - db
    volumes:
      - .:/usr/src/app/
    ports:
      - "8080:8080"
    env_file:
      - ./.env.dev

  db:
    image: postgres:13.4-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev

volumes:
  postgres_data:
