# Generated by Django 3.2.7 on 2021-09-01 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='folder',
            options={'verbose_name': 'Field', 'verbose_name_plural': 'Fields'},
        ),
    ]
