# Generated by Django 3.2.7 on 2021-09-02 01:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='A short, human-friendly identifier for the topic.', max_length=255)),
                ('long_description', models.TextField(blank=True, default='', help_text='A longer description for the topic. Optional.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('documents', models.ManyToManyField(to='documents.Document')),
                ('folders', models.ManyToManyField(to='documents.Folder')),
            ],
            options={
                'verbose_name': 'Topic',
                'verbose_name_plural': 'Topics',
            },
        ),
    ]
