# Generated by Django 3.2.7 on 2021-09-02 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='documents',
            field=models.ManyToManyField(related_name='topics', to='documents.Document'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='folders',
            field=models.ManyToManyField(related_name='topics', to='documents.Folder'),
        ),
    ]
